USE tododev;

CREATE TABLE users
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'users 식별자',
    user_name VARCHAR(100) NOT NULL COMMENT '유저 이름',
    user_email VARCHAR(100) NOT NULL COMMENT '이메일',
    user_password VARCHAR(100) NOT NULL COMMENT '비밀번호',
    create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE todo
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'todo 식별자',
    users_id BIGINT COMMENT 'todo 식별자',
    title VARCHAR(100) NOT NULL COMMENT '제목',
    contents VARCHAR(100) NOT NULL COMMENT '내용',
    create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (users_id) REFERENCES users (id)
);


ALTER TABLE todo AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;

drop table users, todo;

